#! /bin/bash

WORKDIR=$HOME/test
DIST=${1:-$(basename $WORKDIR/*.tar.gz)}
DISTDIR=${DIST%%.tar.gz}

for v in 3.4 3.5 3.6 3.7 3.8 3.9
do
    PYTHON=python$v
    cd $WORKDIR
    rm -rf $DISTDIR
    tar xfz $DIST
    cd $DISTDIR
    $PYTHON setup.py test
done
