#! /bin/bash

WORKDIR=$HOME/test
DIST=${1:-$(basename $WORKDIR/*.tar.gz)}
DISTDIR=${DIST%%.tar.gz}

for v in 2.7 3.6 3.7 3.8 3.9 3.10 3.11 3.12
do
    PYTHON=python$v
    cd $WORKDIR
    rm -rf $DISTDIR
    tar xfz $DIST
    cd $DISTDIR
    $PYTHON setup.py test
done
