#! /bin/bash

. $HOME/.env

for v in 3.6 3.7 3.8 3.9 3.10 3.11 3.12 3.13
do
    PYTHON=python$v
    cd $WORKDIR
    rm -rf $DISTDIR
    tar xfz $DIST
    cd $DISTDIR
    if test -n "$TESTARGS"
    then
	$PYTHON setup.py test --test-args="$TESTARGS"
    else
	$PYTHON setup.py test
    fi
done
